/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.tables.records;


import jooq.steve.db.tables.OcppTag;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OcppTagRecord extends UpdatableRecordImpl<OcppTagRecord> implements Record6<String, String, DateTime, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stevedb.ocpp_tag.id_tag</code>.
     */
    public OcppTagRecord setIdTag(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.ocpp_tag.id_tag</code>.
     */
    public String getIdTag() {
        return (String) get(0);
    }

    /**
     * Setter for <code>stevedb.ocpp_tag.parent_id_tag</code>.
     */
    public OcppTagRecord setParentIdTag(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.ocpp_tag.parent_id_tag</code>.
     */
    public String getParentIdTag() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stevedb.ocpp_tag.expiry_date</code>.
     */
    public OcppTagRecord setExpiryDate(DateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.ocpp_tag.expiry_date</code>.
     */
    public DateTime getExpiryDate() {
        return (DateTime) get(2);
    }

    /**
     * Setter for <code>stevedb.ocpp_tag.note</code>.
     */
    public OcppTagRecord setNote(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.ocpp_tag.note</code>.
     */
    public String getNote() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stevedb.ocpp_tag.ocpp_tag_pk</code>.
     */
    public OcppTagRecord setOcppTagPk(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.ocpp_tag.ocpp_tag_pk</code>.
     */
    public Integer getOcppTagPk() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>stevedb.ocpp_tag.max_active_transaction_count</code>.
     */
    public OcppTagRecord setMaxActiveTransactionCount(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.ocpp_tag.max_active_transaction_count</code>.
     */
    public Integer getMaxActiveTransactionCount() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<String, String, DateTime, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<String, String, DateTime, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return OcppTag.OCPP_TAG.ID_TAG;
    }

    @Override
    public Field<String> field2() {
        return OcppTag.OCPP_TAG.PARENT_ID_TAG;
    }

    @Override
    public Field<DateTime> field3() {
        return OcppTag.OCPP_TAG.EXPIRY_DATE;
    }

    @Override
    public Field<String> field4() {
        return OcppTag.OCPP_TAG.NOTE;
    }

    @Override
    public Field<Integer> field5() {
        return OcppTag.OCPP_TAG.OCPP_TAG_PK;
    }

    @Override
    public Field<Integer> field6() {
        return OcppTag.OCPP_TAG.MAX_ACTIVE_TRANSACTION_COUNT;
    }

    @Override
    public String component1() {
        return getIdTag();
    }

    @Override
    public String component2() {
        return getParentIdTag();
    }

    @Override
    public DateTime component3() {
        return getExpiryDate();
    }

    @Override
    public String component4() {
        return getNote();
    }

    @Override
    public Integer component5() {
        return getOcppTagPk();
    }

    @Override
    public Integer component6() {
        return getMaxActiveTransactionCount();
    }

    @Override
    public String value1() {
        return getIdTag();
    }

    @Override
    public String value2() {
        return getParentIdTag();
    }

    @Override
    public DateTime value3() {
        return getExpiryDate();
    }

    @Override
    public String value4() {
        return getNote();
    }

    @Override
    public Integer value5() {
        return getOcppTagPk();
    }

    @Override
    public Integer value6() {
        return getMaxActiveTransactionCount();
    }

    @Override
    public OcppTagRecord value1(String value) {
        setIdTag(value);
        return this;
    }

    @Override
    public OcppTagRecord value2(String value) {
        setParentIdTag(value);
        return this;
    }

    @Override
    public OcppTagRecord value3(DateTime value) {
        setExpiryDate(value);
        return this;
    }

    @Override
    public OcppTagRecord value4(String value) {
        setNote(value);
        return this;
    }

    @Override
    public OcppTagRecord value5(Integer value) {
        setOcppTagPk(value);
        return this;
    }

    @Override
    public OcppTagRecord value6(Integer value) {
        setMaxActiveTransactionCount(value);
        return this;
    }

    @Override
    public OcppTagRecord values(String value1, String value2, DateTime value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OcppTagRecord
     */
    public OcppTagRecord() {
        super(OcppTag.OCPP_TAG);
    }

    /**
     * Create a detached, initialised OcppTagRecord
     */
    public OcppTagRecord(String idTag, String parentIdTag, DateTime expiryDate, String note, Integer ocppTagPk, Integer maxActiveTransactionCount) {
        super(OcppTag.OCPP_TAG);

        setIdTag(idTag);
        setParentIdTag(parentIdTag);
        setExpiryDate(expiryDate);
        setNote(note);
        setOcppTagPk(ocppTagPk);
        setMaxActiveTransactionCount(maxActiveTransactionCount);
    }
}
