/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.tables.records;


import jooq.steve.db.tables.Reservation;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReservationRecord extends UpdatableRecordImpl<ReservationRecord> implements Record7<Integer, String, DateTime, DateTime, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stevedb.reservation.reservation_pk</code>.
     */
    public ReservationRecord setReservationPk(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.reservation.reservation_pk</code>.
     */
    public Integer getReservationPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stevedb.reservation.id_tag</code>.
     */
    public ReservationRecord setIdTag(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.reservation.id_tag</code>.
     */
    public String getIdTag() {
        return (String) get(1);
    }

    /**
     * Setter for <code>stevedb.reservation.start_datetime</code>.
     */
    public ReservationRecord setStartDatetime(DateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.reservation.start_datetime</code>.
     */
    public DateTime getStartDatetime() {
        return (DateTime) get(2);
    }

    /**
     * Setter for <code>stevedb.reservation.expiry_datetime</code>.
     */
    public ReservationRecord setExpiryDatetime(DateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.reservation.expiry_datetime</code>.
     */
    public DateTime getExpiryDatetime() {
        return (DateTime) get(3);
    }

    /**
     * Setter for <code>stevedb.reservation.status</code>.
     */
    public ReservationRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.reservation.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stevedb.reservation.transaction_pk</code>.
     */
    public ReservationRecord setTransactionPk(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.reservation.transaction_pk</code>.
     */
    public Integer getTransactionPk() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>stevedb.reservation.connector_pk</code>.
     */
    public ReservationRecord setConnectorPk(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.reservation.connector_pk</code>.
     */
    public Integer getConnectorPk() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, String, DateTime, DateTime, String, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, String, DateTime, DateTime, String, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Reservation.RESERVATION.RESERVATION_PK;
    }

    @Override
    public Field<String> field2() {
        return Reservation.RESERVATION.ID_TAG;
    }

    @Override
    public Field<DateTime> field3() {
        return Reservation.RESERVATION.START_DATETIME;
    }

    @Override
    public Field<DateTime> field4() {
        return Reservation.RESERVATION.EXPIRY_DATETIME;
    }

    @Override
    public Field<String> field5() {
        return Reservation.RESERVATION.STATUS;
    }

    @Override
    public Field<Integer> field6() {
        return Reservation.RESERVATION.TRANSACTION_PK;
    }

    @Override
    public Field<Integer> field7() {
        return Reservation.RESERVATION.CONNECTOR_PK;
    }

    @Override
    public Integer component1() {
        return getReservationPk();
    }

    @Override
    public String component2() {
        return getIdTag();
    }

    @Override
    public DateTime component3() {
        return getStartDatetime();
    }

    @Override
    public DateTime component4() {
        return getExpiryDatetime();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public Integer component6() {
        return getTransactionPk();
    }

    @Override
    public Integer component7() {
        return getConnectorPk();
    }

    @Override
    public Integer value1() {
        return getReservationPk();
    }

    @Override
    public String value2() {
        return getIdTag();
    }

    @Override
    public DateTime value3() {
        return getStartDatetime();
    }

    @Override
    public DateTime value4() {
        return getExpiryDatetime();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public Integer value6() {
        return getTransactionPk();
    }

    @Override
    public Integer value7() {
        return getConnectorPk();
    }

    @Override
    public ReservationRecord value1(Integer value) {
        setReservationPk(value);
        return this;
    }

    @Override
    public ReservationRecord value2(String value) {
        setIdTag(value);
        return this;
    }

    @Override
    public ReservationRecord value3(DateTime value) {
        setStartDatetime(value);
        return this;
    }

    @Override
    public ReservationRecord value4(DateTime value) {
        setExpiryDatetime(value);
        return this;
    }

    @Override
    public ReservationRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ReservationRecord value6(Integer value) {
        setTransactionPk(value);
        return this;
    }

    @Override
    public ReservationRecord value7(Integer value) {
        setConnectorPk(value);
        return this;
    }

    @Override
    public ReservationRecord values(Integer value1, String value2, DateTime value3, DateTime value4, String value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReservationRecord
     */
    public ReservationRecord() {
        super(Reservation.RESERVATION);
    }

    /**
     * Create a detached, initialised ReservationRecord
     */
    public ReservationRecord(Integer reservationPk, String idTag, DateTime startDatetime, DateTime expiryDatetime, String status, Integer transactionPk, Integer connectorPk) {
        super(Reservation.RESERVATION);

        setReservationPk(reservationPk);
        setIdTag(idTag);
        setStartDatetime(startDatetime);
        setExpiryDatetime(expiryDatetime);
        setStatus(status);
        setTransactionPk(transactionPk);
        setConnectorPk(connectorPk);
    }
}
