/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.tables.records;


import jooq.steve.db.tables.Users;

import org.joda.time.LocalDate;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record10<Integer, Integer, Integer, String, String, LocalDate, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>stevedb.users.user_pk</code>.
     */
    public UsersRecord setUserPk(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.user_pk</code>.
     */
    public Integer getUserPk() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>stevedb.users.ocpp_tag_pk</code>.
     */
    public UsersRecord setOcppTagPk(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.ocpp_tag_pk</code>.
     */
    public Integer getOcppTagPk() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>stevedb.users.address_pk</code>.
     */
    public UsersRecord setAddressPk(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.address_pk</code>.
     */
    public Integer getAddressPk() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>stevedb.users.first_name</code>.
     */
    public UsersRecord setFirstName(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>stevedb.users.last_name</code>.
     */
    public UsersRecord setLastName(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.last_name</code>.
     */
    public String getLastName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>stevedb.users.birth_day</code>.
     */
    public UsersRecord setBirthDay(LocalDate value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.birth_day</code>.
     */
    public LocalDate getBirthDay() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>stevedb.users.sex</code>.
     */
    public UsersRecord setSex(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.sex</code>.
     */
    public String getSex() {
        return (String) get(6);
    }

    /**
     * Setter for <code>stevedb.users.phone</code>.
     */
    public UsersRecord setPhone(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.phone</code>.
     */
    public String getPhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>stevedb.users.e_mail</code>.
     */
    public UsersRecord setEMail(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.e_mail</code>.
     */
    public String getEMail() {
        return (String) get(8);
    }

    /**
     * Setter for <code>stevedb.users.note</code>.
     */
    public UsersRecord setNote(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>stevedb.users.note</code>.
     */
    public String getNote() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, String, String, LocalDate, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, Integer, String, String, LocalDate, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Users.USERS.USER_PK;
    }

    @Override
    public Field<Integer> field2() {
        return Users.USERS.OCPP_TAG_PK;
    }

    @Override
    public Field<Integer> field3() {
        return Users.USERS.ADDRESS_PK;
    }

    @Override
    public Field<String> field4() {
        return Users.USERS.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return Users.USERS.LAST_NAME;
    }

    @Override
    public Field<LocalDate> field6() {
        return Users.USERS.BIRTH_DAY;
    }

    @Override
    public Field<String> field7() {
        return Users.USERS.SEX;
    }

    @Override
    public Field<String> field8() {
        return Users.USERS.PHONE;
    }

    @Override
    public Field<String> field9() {
        return Users.USERS.E_MAIL;
    }

    @Override
    public Field<String> field10() {
        return Users.USERS.NOTE;
    }

    @Override
    public Integer component1() {
        return getUserPk();
    }

    @Override
    public Integer component2() {
        return getOcppTagPk();
    }

    @Override
    public Integer component3() {
        return getAddressPk();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getLastName();
    }

    @Override
    public LocalDate component6() {
        return getBirthDay();
    }

    @Override
    public String component7() {
        return getSex();
    }

    @Override
    public String component8() {
        return getPhone();
    }

    @Override
    public String component9() {
        return getEMail();
    }

    @Override
    public String component10() {
        return getNote();
    }

    @Override
    public Integer value1() {
        return getUserPk();
    }

    @Override
    public Integer value2() {
        return getOcppTagPk();
    }

    @Override
    public Integer value3() {
        return getAddressPk();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getLastName();
    }

    @Override
    public LocalDate value6() {
        return getBirthDay();
    }

    @Override
    public String value7() {
        return getSex();
    }

    @Override
    public String value8() {
        return getPhone();
    }

    @Override
    public String value9() {
        return getEMail();
    }

    @Override
    public String value10() {
        return getNote();
    }

    @Override
    public UsersRecord value1(Integer value) {
        setUserPk(value);
        return this;
    }

    @Override
    public UsersRecord value2(Integer value) {
        setOcppTagPk(value);
        return this;
    }

    @Override
    public UsersRecord value3(Integer value) {
        setAddressPk(value);
        return this;
    }

    @Override
    public UsersRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public UsersRecord value5(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public UsersRecord value6(LocalDate value) {
        setBirthDay(value);
        return this;
    }

    @Override
    public UsersRecord value7(String value) {
        setSex(value);
        return this;
    }

    @Override
    public UsersRecord value8(String value) {
        setPhone(value);
        return this;
    }

    @Override
    public UsersRecord value9(String value) {
        setEMail(value);
        return this;
    }

    @Override
    public UsersRecord value10(String value) {
        setNote(value);
        return this;
    }

    @Override
    public UsersRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, LocalDate value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer userPk, Integer ocppTagPk, Integer addressPk, String firstName, String lastName, LocalDate birthDay, String sex, String phone, String eMail, String note) {
        super(Users.USERS);

        setUserPk(userPk);
        setOcppTagPk(ocppTagPk);
        setAddressPk(addressPk);
        setFirstName(firstName);
        setLastName(lastName);
        setBirthDay(birthDay);
        setSex(sex);
        setPhone(phone);
        setEMail(eMail);
        setNote(note);
    }
}
