/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.tables;


import de.rwth.idsg.steve.utils.DateTimeConverter;

import jooq.steve.db.Stevedb;
import jooq.steve.db.enums.EventActor;
import jooq.steve.db.tables.records.TransactionRecord;

import org.joda.time.DateTime;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction extends TableImpl<TransactionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>stevedb.transaction</code>
     */
    public static final Transaction TRANSACTION = new Transaction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TransactionRecord> getRecordType() {
        return TransactionRecord.class;
    }

    /**
     * The column <code>stevedb.transaction.transaction_pk</code>.
     */
    public final TableField<TransactionRecord, Integer> TRANSACTION_PK = createField(DSL.name("transaction_pk"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stevedb.transaction.connector_pk</code>.
     */
    public final TableField<TransactionRecord, Integer> CONNECTOR_PK = createField(DSL.name("connector_pk"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>stevedb.transaction.id_tag</code>.
     */
    public final TableField<TransactionRecord, String> ID_TAG = createField(DSL.name("id_tag"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stevedb.transaction.start_event_timestamp</code>.
     */
    public final TableField<TransactionRecord, DateTime> START_EVENT_TIMESTAMP = createField(DSL.name("start_event_timestamp"), SQLDataType.TIMESTAMP(6), this, "", new DateTimeConverter());

    /**
     * The column <code>stevedb.transaction.start_timestamp</code>.
     */
    public final TableField<TransactionRecord, DateTime> START_TIMESTAMP = createField(DSL.name("start_timestamp"), SQLDataType.TIMESTAMP(6), this, "", new DateTimeConverter());

    /**
     * The column <code>stevedb.transaction.start_value</code>.
     */
    public final TableField<TransactionRecord, String> START_VALUE = createField(DSL.name("start_value"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stevedb.transaction.stop_event_actor</code>.
     */
    public final TableField<TransactionRecord, EventActor> STOP_EVENT_ACTOR = createField(DSL.name("stop_event_actor"), SQLDataType.VARCHAR.asEnumDataType(jooq.steve.db.enums.EventActor.class), this, "");

    /**
     * The column <code>stevedb.transaction.stop_event_timestamp</code>.
     */
    public final TableField<TransactionRecord, DateTime> STOP_EVENT_TIMESTAMP = createField(DSL.name("stop_event_timestamp"), SQLDataType.TIMESTAMP(6), this, "", new DateTimeConverter());

    /**
     * The column <code>stevedb.transaction.stop_timestamp</code>.
     */
    public final TableField<TransactionRecord, DateTime> STOP_TIMESTAMP = createField(DSL.name("stop_timestamp"), SQLDataType.TIMESTAMP(6), this, "", new DateTimeConverter());

    /**
     * The column <code>stevedb.transaction.stop_value</code>.
     */
    public final TableField<TransactionRecord, String> STOP_VALUE = createField(DSL.name("stop_value"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>stevedb.transaction.stop_reason</code>.
     */
    public final TableField<TransactionRecord, String> STOP_REASON = createField(DSL.name("stop_reason"), SQLDataType.VARCHAR(255), this, "");

    private Transaction(Name alias, Table<TransactionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Transaction(Name alias, Table<TransactionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view \"transaction\" as  SELECT tx1.transaction_pk,\n    tx1.connector_pk,\n    tx1.id_tag,\n    tx1.event_timestamp AS start_event_timestamp,\n    tx1.start_timestamp,\n    tx1.start_value,\n    tx2.event_actor AS stop_event_actor,\n    tx2.event_timestamp AS stop_event_timestamp,\n    tx2.stop_timestamp,\n    tx2.stop_value,\n    tx2.stop_reason\n   FROM (stevedb.transaction_start tx1\n     LEFT JOIN ( SELECT s1.transaction_pk,\n            s1.event_timestamp,\n            s1.event_actor,\n            s1.stop_timestamp,\n            s1.stop_value,\n            s1.stop_reason\n           FROM stevedb.transaction_stop s1\n          WHERE (s1.event_timestamp = ( SELECT max(s2.event_timestamp) AS max\n                   FROM stevedb.transaction_stop s2\n                  WHERE (s1.transaction_pk = s2.transaction_pk)))\n          GROUP BY s1.transaction_pk, s1.event_timestamp) tx2 ON ((tx1.transaction_pk = tx2.transaction_pk)));"));
    }

    /**
     * Create an aliased <code>stevedb.transaction</code> table reference
     */
    public Transaction(String alias) {
        this(DSL.name(alias), TRANSACTION);
    }

    /**
     * Create an aliased <code>stevedb.transaction</code> table reference
     */
    public Transaction(Name alias) {
        this(alias, TRANSACTION);
    }

    /**
     * Create a <code>stevedb.transaction</code> table reference
     */
    public Transaction() {
        this(DSL.name("transaction"), null);
    }

    public <O extends Record> Transaction(Table<O> child, ForeignKey<O, TransactionRecord> key) {
        super(child, key, TRANSACTION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Stevedb.STEVEDB;
    }

    @Override
    public Transaction as(String alias) {
        return new Transaction(DSL.name(alias), this);
    }

    @Override
    public Transaction as(Name alias) {
        return new Transaction(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(String name) {
        return new Transaction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Transaction rename(Name name) {
        return new Transaction(name, null);
    }

    // -------------------------------------------------------------------------
    // Row11 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row11<Integer, Integer, String, DateTime, DateTime, String, EventActor, DateTime, DateTime, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }
}
