/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db.enums;


import jooq.steve.db.Stevedb;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EventActor implements EnumType {

    station("station"),

    manual("manual");

    private final String literal;

    private EventActor(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Stevedb.STEVEDB;
    }

    @Override
    public String getName() {
        return "event_actor";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static EventActor lookupLiteral(String literal) {
        return EnumType.lookupLiteral(EventActor.class, literal);
    }
}
