/*
 * This file is generated by jOOQ.
 */
package jooq.steve.db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in stevedb.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>stevedb.transaction_transaction_pk_seq</code>
     */
    public static final Sequence<Integer> TRANSACTION_TRANSACTION_PK_SEQ = Internal.createSequence("transaction_transaction_pk_seq", Stevedb.STEVEDB, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>stevedb.users_user_pk_seq</code>
     */
    public static final Sequence<Integer> USERS_USER_PK_SEQ = Internal.createSequence("users_user_pk_seq", Stevedb.STEVEDB, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>stevedb.users_user_pk_seq1</code>
     */
    public static final Sequence<Integer> USERS_USER_PK_SEQ1 = Internal.createSequence("users_user_pk_seq1", Stevedb.STEVEDB, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
